# Generated by Django 5.1.6 on 2025-02-24 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('customerCode', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('orderNumber', models.CharField(max_length=255)),
                ('orderDate', models.DateField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('itemCode', models.AutoField(primary_key=True, serialize=False)),
                ('itemName', models.DateField(max_length=255)),
                ('description', models.DateField(max_length=255)),
                ('unitPrice', models.FloatField(max_length=255)),
            ],
        ),
    ]
