# Generated by Django 5.1.6 on 2025-02-24 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ERMapp', '0002_remove_customer_orderdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='description',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='item',
            name='itemName',
            field=models.CharField(max_length=255),
        ),
    ]
