# Generated by Django 5.1.6 on 2025-02-25 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ERMapp', '0004_item_stock'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('itemCode', models.IntegerField(null=True)),
                ('itemName', models.CharField(max_length=255)),
                ('quantity', models.IntegerField(null=True)),
                ('unitPrice', models.FloatField(max_length=255)),
                ('stock', models.IntegerField(null=True)),
                ('total', models.FloatField(max_length=255)),
            ],
        ),
    ]
