# Generated by Django 5.0.6 on 2025-02-25 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ERMapp', '0005_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='customerCode',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='customerName',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='customerOrderDate',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='customerOrderNumber',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
